### ISSUE TITLE
Split the page into sections - content/Storymap_steps.html

### ISSUE THREAD

**Issue by ect123** [ubc-library-rc/gis-ArcGIS-Storymap#1]
This page could be split into sections that correspond to the block and features list: 

    Configure themes and add a logo
    Preview the Storymap
    Add basic features
        Add title, subtitle, and Text
        Add a Botton
        Add a Separator
    Embed media
        Image
        Video
        Add a web map
        Swipe
        Timeline
    Embed immersive content
        Sidecar
        map tour
        Slideshow
    Publish and share the story map

Subsections don't need their own page. Follow the order on the page for sections because they don't match the list above.

**Comment by Xilin-Wan** [comment]
This has been resolved
