### ISSUE TITLE
text edits

### ISSUE THREAD

**Issue by lilydemet** [ubc-library-rc/gis-ArcGIS-Storymap#5]
Outline:

Is this workshop more introductory to the 2nd visualizing Data in ArcGIS Online workshop, or are can they be completed independently? Perhaps name and link the other, or, if it's forthcoming, leave out mention for now.

since there are multiple sections in the outline structured into bullets, to consolidate I'd recommend incorporating the 3 bullets from Workshop Outline into the introductory paragraph. Participants may want to know what the workshop will entail before what they will learn. 

Remove -ing from Learning objectives
I don't think the indented bullet points are needed - the specifics may be overwhelming for participants who don't yet have context for terms such as "swipe" and "sidecar". The main bullets are probably sufficient!

At the bottom of the page, downloading workshop data and preparing images can go under Set-Up, rather than Prerequisite. Creating an AGOL account could be step 1. then downloading data step 2. 

--

**Comment by Xilin-Wan** [comment]
Thank you for your comments! I will consider and make changes.
